# Generated by Django 4.1 on 2022-08-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0002_alter_voiture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
