# Generated by Django 3.2.14 on 2022-09-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voitures', '0003_alter_voiture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='mark',
            field=models.CharField(choices=[('PEOGEOT', 'Peogot'), ('RENAULT', 'Renault'), ('RR', 'Range Rover')], max_length=10),
        ),
    ]
